[WIP] Organizing Top Menu and adding 2021 Hack Week info
PlasmaPy/plasma-hack-week pull request #9
Opened 2021-04-07 22:03 UTC by rocco8773

This PR organizes the Top Menu and creates the initial 2021 Hack Week pages.

2021-04-07 22:16 UTC, namurphy commented on pages/2021/social.md
> +Since this year's Hack Week if purely virtual, we're hoping to schedule in
```suggestion
Since this year's Hack Week is purely virtual, we're hoping to schedule in
```

2021-04-07 22:17 UTC, namurphy commented on pages/2021/about.md
> +hold prequel tutorialson tpics such as Python, git & GitHub, contributing to
```suggestion
hold prequel tutorials on topics such as Python, git & GitHub, contributing to
```

2021-04-07 22:18 UTC, namurphy commented on pages/2021/about.md
> +Welcome to the inaugural **Plasma Hack Week**!!  Our first even will be held
```suggestion
Welcome to the inaugural **Plasma Hack Week**!!  Our first event will be held
```

2021-04-21 19:33 UTC, rocco8773 commented on pages/2021/about.md
> +In the week leading up to the **Plsama Hack Week**, a few more fundamentally
```suggestion
In the week leading up to the **Plasma Hack Week**, a few more fundamentally
```

2021-04-21 19:55 UTC, svincena commented on pages/2021/schedule.md
> +unstructured free hacking time, and social time.  All event in a given day will
```suggestion
unstructured free hacking time, and social time.  All events in a given day will
```

2021-04-21 19:56 UTC, svincena reviewed
typo

2021-04-22 00:47 UTC, svincena requested changes
Typo fixes

2021-04-22 00:47 UTC, svincena commented on pages/2021/about.md
> +to software engineering skills.  These topics will be present through both
```suggestion
to software engineering skills.  These topics will be presented through both
```

2021-04-22 00:47 UTC, svincena commented on pages/2021/about.md
> +to software engineering skills.  These topics will be present through both
```suggestion
to software engineering skills.  These topics will be presented through both
```

2021-04-22 00:47 UTC, svincena commented on pages/2021/schedule.md
> +Please stay tuned to this page, since the refined scheduled will be posted
```suggestion
Please stay tuned to this page, since the refined schedule will be posted
```

2021-04-22 00:47 UTC, svincena commented on pages/2021/social.md
> +loose th social aspect related to in person events.  In an effort to regain
```suggestion
loose the social aspect related to in-person events.  In an effort to regain
```

2021-04-22 00:47 UTC, svincena commented on pages/contact.md
> +If you have any question about the **Plasma Hack Week** or want to get involved,
```suggestion
If you have any questions about the **Plasma Hack Week** or want to get involved,
```

2021-04-22 18:30 UTC, namurphy approved these changes

2021-04-22 18:30 UTC, merged

2021-04-27 15:57 UTC, smithsp commented on pages/2021/schedule.md
> +not exceed 5 hours, but we highly encourage any extend breakout discussions that
`any extend` -> `any extended`

2021-04-27 15:57 UTC, smithsp commented on pages/2021/schedule.md
> +may be promoted from the day's activities.
`promoted from` -> `promoted by`

2021-04-27 15:57 UTC, smithsp commented on pages/2021/social.md
> +Since this year's Hack Week is purely virtual, and as such, we inherently
`Since this` -> `This`